security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

salesforce:
  b2c:
    client:
      clientId: xxx.QEg6pPEnxxxxCZ22IU
      clientSecret: 6805xxxxxxx4418
      accessTokenUri: https://devec2-espaceclient-adie.cs15.force.com/services/oauth2/token
      userAuthorizationUri: https://devec2-espaceclient-adie.cs15.force.com/services/oauth2/authorize
      clientAuthenticationScheme: form
      authenticationScheme: query
      tokenName: oauth_token
    resource:
      userInfoUri: https://test.salesforce.com/id/{COMMUNITY_ID}/{USER_ID}/
  b2b:
    client:
      clientId: xxxx.QEg6pPEnCZ22IU
      clientSecret: 68057xxxx8
      accessTokenUri: https://cs15.salesforce.com/services/oauth2/token
      userAuthorizationUri: https://cs15.salesforce.com/services/oauth2/authorize
      clientAuthenticationScheme: form
      authenticationScheme: query
      tokenName: oauth_token
    resource:
      userInfoUri: https://test.salesforce.com/id/{COMMUNITY_ID}/{USER_ID}/
logging:
  level:
    org.springframework.security: DEBUG
