security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

salesforce:
  b2c:
    client:
      clientId: 3MVG9dPGzpc3kWydcitmO_I5XRa8IXTCnEGMfuYLqOUuSscVupHJc8HarX1d845LVyc4iK.QEg6pPEnCZ22IU
      clientSecret: 680571769674884418
      accessTokenUri: https://devec2-espaceclient-adie.cs15.force.com/services/oauth2/token
      userAuthorizationUri: https://devec2-espaceclient-adie.cs15.force.com/services/oauth2/authorize
      clientAuthenticationScheme: form
      authenticationScheme: query
      tokenName: oauth_token
    resource:
      userInfoUri: https://test.salesforce.com/id/{ORGANISATION_ID}/{USER_ID}/
  b2b:
    client:
      clientId: 3MVG9dPGzpc3kWydcitmO_I5XRa8IXTCnEGMfuYLqOUuSscVupHJc8HarX1d845LVyc4iK.QEg6pPEnCZ22IU
      clientSecret: 680571769674884418
      accessTokenUri: https://cs15.salesforce.com/services/oauth2/token
      userAuthorizationUri: https://cs15.salesforce.com/services/oauth2/authorize
      clientAuthenticationScheme: form
      authenticationScheme: query
      tokenName: oauth_token
    resource:
      userInfoUri: https://test.salesforce.com/id/{ORGANISATION_ID}/{USER_ID}/
logging:
  level:
    org.springframework.security: DEBUG
